-- CineTonight Movie Intelligence — BATCH 2 DRAFTS (1 Sep 2026)
-- Same rule as batch 1: read every row, edit freely, then run in the
-- Supabase SQL editor. Upsert — safe to re-run. Change editor for your
-- own byline. Avengers: Doomsday stays absent until it releases.

insert into public.movie_intel (id, verdict_headline, watch_if, skip_if, chips, mood, pace, intensity, attention, themes, vibe, expect, best_for_who, best_for_context, best_for_caution, take_title, take_body, alt_id, alt_reasons, episode_rhythm, hook_expectation, editor)
values ('mutiny', 'Ninety-five minutes of Statham doing exactly what you hired him for.', '["You want fight choreography first and questions never", "A lean, confined-setting action ride sounds like tonight"]'::jsonb, '["You need story or character depth with your punches", "You''ve seen enough interchangeable Statham vehicles"]'::jsonb, '["Action", "Lean", "Casual"]'::jsonb, 'Adrenaline', 'fast', 'high', 'casual', '["Framed man", "Survival at sea", "Trafficking ring"]'::jsonb, 'Bone-crunching and unpretentious', '[{"label": "Action", "value": "Constant", "level": 3}, {"label": "Story", "value": "Thin", "level": 1}, {"label": "Tension", "value": "Steady", "level": 2}, {"label": "Humor", "value": "Dry", "level": 1}]'::jsonb, 'Action fans who know exactly what a Statham film is', 'A no-thinking weeknight with snacks', 'Critics split — it delivers fists, not surprises', 'The cargo ship does half the work', 'The confined-ship setting gives the fights real invention, the editing keeps two threads of tension running, and at 95 minutes it never overstays. Nobody involved is pretending this is more than a delivery vehicle for bone-snapping — reviewers split on whether that''s enough. If it is for you, it absolutely delivers.', 'facing-el-chapo', '["Grounded tension instead of pure fists", "Similar runtime, more story"]'::jsonb, null, null, 'CineTonight Editorial')
on conflict (id) do update set verdict_headline=excluded.verdict_headline, watch_if=excluded.watch_if, skip_if=excluded.skip_if, chips=excluded.chips, mood=excluded.mood, pace=excluded.pace, intensity=excluded.intensity, attention=excluded.attention, themes=excluded.themes, vibe=excluded.vibe, expect=excluded.expect, best_for_who=excluded.best_for_who, best_for_context=excluded.best_for_context, best_for_caution=excluded.best_for_caution, take_title=excluded.take_title, take_body=excluded.take_body, alt_id=excluded.alt_id, alt_reasons=excluded.alt_reasons, episode_rhythm=excluded.episode_rhythm, hook_expectation=excluded.hook_expectation, editor=excluded.editor, updated_at=now(), reviewed_at=now();

insert into public.movie_intel (id, verdict_headline, watch_if, skip_if, chips, mood, pace, intensity, attention, themes, vibe, expect, best_for_who, best_for_context, best_for_caution, take_title, take_body, alt_id, alt_reasons, episode_rhythm, hook_expectation, editor)
values ('insidious-out-of-the-further', 'The scariest Insidious sequel — familiar jumps, a few genuinely great set pieces.', '["You want reliable jump-scare horror that works with the lights off", "You''re new to Insidious — this entry stands alone fine"]'::jsonb, '["Predictable horror plotting spoils it for you", "You want dread over jolts"]'::jsonb, '["Jump scares", "Accessible", "Normal"]'::jsonb, 'Jumpy', 'steady', 'high', 'normal', '["The Further", "Grief", "Haunted family"]'::jsonb, 'Funhouse-scary with surprising laughs', '[{"label": "Scares", "value": "High", "level": 3}, {"label": "Story", "value": "Predictable", "level": 1}, {"label": "Humor", "value": "Unexpected", "level": 2}, {"label": "Gore", "value": "Restrained", "level": 1}]'::jsonb, 'Jump-scare fans and franchise faithful', 'Group watch — it''s built for shared jolts', 'The third act loses steam and gets murky', 'Judged as a scare machine, it works', 'Jacob Chase builds tension properly, Amelia Eve sells every ounce of fear, and one liminal-space set piece is among the franchise''s best. The script is as predictable as they come and the effects wobble late — but as a Friday-night scare delivery system with friends, it does its job and then some.', 'obsession', '["For horror that unsettles instead of jolts", "Stronger story, heavier themes"]'::jsonb, null, null, 'CineTonight Editorial')
on conflict (id) do update set verdict_headline=excluded.verdict_headline, watch_if=excluded.watch_if, skip_if=excluded.skip_if, chips=excluded.chips, mood=excluded.mood, pace=excluded.pace, intensity=excluded.intensity, attention=excluded.attention, themes=excluded.themes, vibe=excluded.vibe, expect=excluded.expect, best_for_who=excluded.best_for_who, best_for_context=excluded.best_for_context, best_for_caution=excluded.best_for_caution, take_title=excluded.take_title, take_body=excluded.take_body, alt_id=excluded.alt_id, alt_reasons=excluded.alt_reasons, episode_rhythm=excluded.episode_rhythm, hook_expectation=excluded.hook_expectation, editor=excluded.editor, updated_at=now(), reviewed_at=now();

insert into public.movie_intel (id, verdict_headline, watch_if, skip_if, chips, mood, pace, intensity, attention, themes, vibe, expect, best_for_who, best_for_context, best_for_caution, take_title, take_body, alt_id, alt_reasons, episode_rhythm, hook_expectation, editor)
values ('facing-el-chapo', 'A grounded, tightening-vise crime thriller that earns its tension honestly.', '["Realistic crime tension beats spectacle for you", "One-situation thrillers (the transport must get through) are your thing"]'::jsonb, '["Slow character-first openings lose you", "You want action-movie pacing throughout"]'::jsonb, '["Tense", "Grounded", "Focused"]'::jsonb, 'Tense', 'steady', 'moderate', 'focused', '["Duty under threat", "Corruption", "One dangerous night"]'::jsonb, 'Realistic pressure — when, not if, the gun goes off', '[{"label": "Tension", "value": "High", "level": 3}, {"label": "Action", "value": "Measured", "level": 2}, {"label": "Emotion", "value": "Present", "level": 2}, {"label": "Spectacle", "value": "Low", "level": 1}]'::jsonb, 'Crime-thriller viewers who prize believability', 'A focused solo or partner watch', 'The opening takes its time before the vise tightens', 'Restraint is the weapon here', 'The film''s trick is refusing melodrama: the cartel behaves plausibly, the two officers rub against each other like real partners, and the threat escalates by inches. The setup drags a little, but once the transport starts moving the tension doesn''t let go — a genuinely solid entry in the grounded crime lane.', 'mutiny', '["Same lean runtime, fists-first instead of nerves-first"]'::jsonb, null, null, 'CineTonight Editorial')
on conflict (id) do update set verdict_headline=excluded.verdict_headline, watch_if=excluded.watch_if, skip_if=excluded.skip_if, chips=excluded.chips, mood=excluded.mood, pace=excluded.pace, intensity=excluded.intensity, attention=excluded.attention, themes=excluded.themes, vibe=excluded.vibe, expect=excluded.expect, best_for_who=excluded.best_for_who, best_for_context=excluded.best_for_context, best_for_caution=excluded.best_for_caution, take_title=excluded.take_title, take_body=excluded.take_body, alt_id=excluded.alt_id, alt_reasons=excluded.alt_reasons, episode_rhythm=excluded.episode_rhythm, hook_expectation=excluded.hook_expectation, editor=excluded.editor, updated_at=now(), reviewed_at=now();

insert into public.movie_intel (id, verdict_headline, watch_if, skip_if, chips, mood, pace, intensity, attention, themes, vibe, expect, best_for_who, best_for_context, best_for_caution, take_title, take_body, alt_id, alt_reasons, episode_rhythm, hook_expectation, editor)
values ('lanterns', 'A superhero show wearing a detective drama''s clothes — and better for it.', '["Character-driven mystery appeals more than CGI battles", "Two great leads circling each other is your kind of show", "True Detective-style small-town unease sounds right"]'::jsonb, '["You want classic ring-slinging superhero action every episode", "Timeline-jumping structures annoy you"]'::jsonb, '["Prestige TV", "Mystery", "Focused"]'::jsonb, 'Brooding', 'patient', 'moderate', 'focused', '["Legacy vs ambition", "Race and opportunity", "The cost of heroism"]'::jsonb, 'Slow-burn buddy-cop drama under a superhero sky', '[{"label": "Character", "value": "Deep", "level": 3}, {"label": "Mystery", "value": "Central", "level": 3}, {"label": "Action", "value": "Occasional", "level": 1}, {"label": "Spectacle", "value": "Restrained", "level": 2}]'::jsonb, 'Viewers who liked the idea of superheroes more in Watchmen than in crossovers', 'An attentive evenings binge — it rewards focus', 'Exposition occasionally lands leaden and over-explained', 'The rivalry is the engine', 'Kyle Chandler''s tired veteran against Aaron Pierre''s hungry recruit is the show: everything good flows from that friction, across three timelines and one Nebraska mystery. It reaches for Watchmen and doesn''t quite grab it, and it explains its themes more than it needs to — but as grounded superhero television, this is the good stuff.', 'house-of-the-dragon', '["Also prestige-scale TV, spectacle-first instead of mystery-first"]'::jsonb, 'serialized', 'Give it 2 episodes — it''s a mystery show first, and the hook sets by then', 'CineTonight Editorial')
on conflict (id) do update set verdict_headline=excluded.verdict_headline, watch_if=excluded.watch_if, skip_if=excluded.skip_if, chips=excluded.chips, mood=excluded.mood, pace=excluded.pace, intensity=excluded.intensity, attention=excluded.attention, themes=excluded.themes, vibe=excluded.vibe, expect=excluded.expect, best_for_who=excluded.best_for_who, best_for_context=excluded.best_for_context, best_for_caution=excluded.best_for_caution, take_title=excluded.take_title, take_body=excluded.take_body, alt_id=excluded.alt_id, alt_reasons=excluded.alt_reasons, episode_rhythm=excluded.episode_rhythm, hook_expectation=excluded.hook_expectation, editor=excluded.editor, updated_at=now(), reviewed_at=now();

insert into public.movie_intel (id, verdict_headline, watch_if, skip_if, chips, mood, pace, intensity, attention, themes, vibe, expect, best_for_who, best_for_context, best_for_caution, take_title, take_body, alt_id, alt_reasons, episode_rhythm, hook_expectation, editor)
values ('spider-man-brand-new-day', 'The most grounded Spider-Man yet — big feelings, great fights, a little too much of everything.', '["You want street-level Spidey instead of multiverse math", "Holland''s Peter finally getting dramatic weight interests you", "Top-tier MCU action is reason enough"]'::jsonb, '["Superhero fatigue is real and 2.5 hours is a lot", "You want light, quippy Spider-Man all the way through"]'::jsonb, '["Superhero", "Grounded", "Normal"]'::jsonb, 'Earnest', 'steady', 'moderate', 'normal', '["Isolation", "Responsibility", "Street-level heroism"]'::jsonb, 'Mature and physical — Spidey with bruises', '[{"label": "Action", "value": "Excellent", "level": 3}, {"label": "Emotion", "value": "Strong", "level": 2}, {"label": "Humor", "value": "Present", "level": 2}, {"label": "Length", "value": "Overstuffed", "level": 1}]'::jsonb, 'MCU viewers wanting substance with the spectacle', 'A full-evening event watch', 'Feels half an hour too long, and the villain subplot wanders', 'Growing up suits him', 'Cretton shoots the best-looking Spider-Man of the era, Holland finally gets real dramatic meat, and the Bernthal pairing is comedy gold with an edge. It''s overstuffed — the villain detour costs the relationships time, and the runtime shows. But when it''s Peter, the streets and the fights, it''s the franchise at its most alive.', 'the-odyssey', '["Another full-evening epic — mythic scale instead of Marvel"]'::jsonb, null, null, 'CineTonight Editorial')
on conflict (id) do update set verdict_headline=excluded.verdict_headline, watch_if=excluded.watch_if, skip_if=excluded.skip_if, chips=excluded.chips, mood=excluded.mood, pace=excluded.pace, intensity=excluded.intensity, attention=excluded.attention, themes=excluded.themes, vibe=excluded.vibe, expect=excluded.expect, best_for_who=excluded.best_for_who, best_for_context=excluded.best_for_context, best_for_caution=excluded.best_for_caution, take_title=excluded.take_title, take_body=excluded.take_body, alt_id=excluded.alt_id, alt_reasons=excluded.alt_reasons, episode_rhythm=excluded.episode_rhythm, hook_expectation=excluded.hook_expectation, editor=excluded.editor, updated_at=now(), reviewed_at=now();
