-- CineTonight Movie Intelligence — BATCH 1 DRAFTS (1 Sep 2026)
-- Reviewed-by-you is the rule: read every row below, edit any wording you
-- disagree with, then run this in the Supabase SQL editor. Re-running after
-- edits is safe (upsert). Editor is set to 'CineTonight Editorial' — change
-- it if you want your own byline on the Take.
-- Unreleased titles (Avengers: Doomsday) are deliberately absent.

insert into public.movie_intel (id, verdict_headline, watch_if, skip_if, chips, mood, pace, intensity, attention, themes, vibe, expect, best_for_who, best_for_context, best_for_caution, take_title, take_body, alt_id, alt_reasons, episode_rhythm, hook_expectation, editor)
values ('the-odyssey', 'A colossal big-screen epic that rewards patience and full attention.', '["You want a grand, serious spectacle that fills the whole evening", "You loved Oppenheimer''s scale and craft", "Mythology retold with real emotional weight appeals to you"]'::jsonb, '["You want something light or under two hours tonight", "Slow, dialogue-heavy stretches test your patience"]'::jsonb, '["Epic", "Slow build", "Focused"]'::jsonb, 'Awe-inspiring', 'patient', 'moderate', 'focused', '["Homecoming", "Fate and responsibility", "War''s aftermath"]'::jsonb, 'Vast and serious — a myth told with full weight', '[{"label": "Spectacle", "value": "Huge", "level": 3}, {"label": "Emotion", "value": "Strong", "level": 2}, {"label": "Action", "value": "Steady", "level": 2}, {"label": "Humor", "value": "Light", "level": 1}]'::jsonb, 'Anyone who wants cinema at full scale', 'A committed solo or partner watch with the lights off', 'At nearly three hours, not a casual weeknight pick', 'Nolan gives the oldest story real weight', 'The draw here is scale with feeling: the sea, the storms and the homecoming all land with physical force, and the ensemble keeps the myth human. It asks three hours and your full attention, and a few talky stretches drag — but this is the kind of film big screens exist for, and for once the emphatic reception mostly holds.', null, '[]'::jsonb, null, null, 'CineTonight Editorial')
on conflict (id) do update set verdict_headline=excluded.verdict_headline, watch_if=excluded.watch_if, skip_if=excluded.skip_if, chips=excluded.chips, mood=excluded.mood, pace=excluded.pace, intensity=excluded.intensity, attention=excluded.attention, themes=excluded.themes, vibe=excluded.vibe, expect=excluded.expect, best_for_who=excluded.best_for_who, best_for_context=excluded.best_for_context, best_for_caution=excluded.best_for_caution, take_title=excluded.take_title, take_body=excluded.take_body, alt_id=excluded.alt_id, alt_reasons=excluded.alt_reasons, episode_rhythm=excluded.episode_rhythm, hook_expectation=excluded.hook_expectation, editor=excluded.editor, updated_at=now(), reviewed_at=now();

insert into public.movie_intel (id, verdict_headline, watch_if, skip_if, chips, mood, pace, intensity, attention, themes, vibe, expect, best_for_who, best_for_context, best_for_caution, take_title, take_body, alt_id, alt_reasons, episode_rhythm, hook_expectation, editor)
values ('toy-story-5', 'A warm, funny family night that plays safer than Pixar''s best.', '["Family movie night with kids of any age", "You grew up with Woody and Jessie and want one more round", "You want reliable laughs with some real heart"]'::jsonb, '["You''re hoping for Toy Story 3-level emotional depth"]'::jsonb, '["Feel-good", "Family", "Casual"]'::jsonb, 'Warm', 'steady', 'low', 'casual', '["Screens vs play", "Belonging", "Growing up"]'::jsonb, 'Bright, funny and comfortably familiar', '[{"label": "Humor", "value": "High", "level": 3}, {"label": "Emotion", "value": "Present", "level": 2}, {"label": "Action", "value": "Playful", "level": 2}, {"label": "Complexity", "value": "Low", "level": 1}]'::jsonb, 'Families and longtime fans', 'A weekend evening with kids', 'Adults may find its big ideas softened', 'Pixar plays the hits — and mostly gets away with it', 'The tablet-versus-toys premise is a genuinely good hook, Jessie finally gets the spotlight, and the new characters earn their laughs. It raises sharper questions about screens than it is willing to answer, settling for comfort where the best Toy Story films risked heartbreak. As a family night it delivers; as a Pixar milestone it sits a step below the trilogy.', null, '[]'::jsonb, null, null, 'CineTonight Editorial')
on conflict (id) do update set verdict_headline=excluded.verdict_headline, watch_if=excluded.watch_if, skip_if=excluded.skip_if, chips=excluded.chips, mood=excluded.mood, pace=excluded.pace, intensity=excluded.intensity, attention=excluded.attention, themes=excluded.themes, vibe=excluded.vibe, expect=excluded.expect, best_for_who=excluded.best_for_who, best_for_context=excluded.best_for_context, best_for_caution=excluded.best_for_caution, take_title=excluded.take_title, take_body=excluded.take_body, alt_id=excluded.alt_id, alt_reasons=excluded.alt_reasons, episode_rhythm=excluded.episode_rhythm, hook_expectation=excluded.hook_expectation, editor=excluded.editor, updated_at=now(), reviewed_at=now();

insert into public.movie_intel (id, verdict_headline, watch_if, skip_if, chips, mood, pace, intensity, attention, themes, vibe, expect, best_for_who, best_for_context, best_for_caution, take_title, take_body, alt_id, alt_reasons, episode_rhythm, hook_expectation, editor)
values ('evil-dead-burn', 'Relentless, inventive gore — a gift for horror fans and a hard no for everyone else.', '["You love the Evil Dead brand of blood-soaked mayhem", "Practical effects and creative kills are your thing"]'::jsonb, '["Graphic violence puts you off — this one is relentless", "You want scares without the splatter"]'::jsonb, '["Extreme gore", "Dark humor", "Fast"]'::jsonb, 'Ferocious', 'fast', 'high', 'normal', '["Possession", "Family dysfunction", "Survival"]'::jsonb, 'Grisly, kinetic and blackly funny', '[{"label": "Gore", "value": "Extreme", "level": 3}, {"label": "Scares", "value": "High", "level": 3}, {"label": "Humor", "value": "Pitch-black", "level": 2}, {"label": "Story", "value": "Lean", "level": 1}]'::jsonb, 'Committed horror fans', 'Late night, sound up, squeamish friends warned', 'Among the franchise''s most graphic entries', 'The franchise''s nastiest — in a good way', 'Vaniček directs with real energy — whip cameras, practical effects, everyday objects turned into weapons — and threads a surprisingly serious streak about abuse through the mayhem. The ending doesn''t quite match the ride, and the violence really is relentless. If that sentence excites you, this delivers; if it worries you, believe it.', 'obsession', '["Also 2026 horror, more psychological than splatter", "For dread that builds instead of blood that flies"]'::jsonb, null, null, 'CineTonight Editorial')
on conflict (id) do update set verdict_headline=excluded.verdict_headline, watch_if=excluded.watch_if, skip_if=excluded.skip_if, chips=excluded.chips, mood=excluded.mood, pace=excluded.pace, intensity=excluded.intensity, attention=excluded.attention, themes=excluded.themes, vibe=excluded.vibe, expect=excluded.expect, best_for_who=excluded.best_for_who, best_for_context=excluded.best_for_context, best_for_caution=excluded.best_for_caution, take_title=excluded.take_title, take_body=excluded.take_body, alt_id=excluded.alt_id, alt_reasons=excluded.alt_reasons, episode_rhythm=excluded.episode_rhythm, hook_expectation=excluded.hook_expectation, editor=excluded.editor, updated_at=now(), reviewed_at=now();

insert into public.movie_intel (id, verdict_headline, watch_if, skip_if, chips, mood, pace, intensity, attention, themes, vibe, expect, best_for_who, best_for_context, best_for_caution, take_title, take_body, alt_id, alt_reasons, episode_rhythm, hook_expectation, editor)
values ('obsession', 'A wish gone wrong becomes one of the year''s most unnerving horror films.', '["You want horror that gets under your skin rather than just jump-scares", "Character-driven psychological dread is your lane"]'::jsonb, '["Obsessive-stalker themes hit too close to be fun", "You need your horror light"]'::jsonb, '["Unnerving", "Slow burn", "Focused"]'::jsonb, 'Unsettling', 'steady', 'high', 'focused', '["Obsession", "Wishes and consequences", "Control"]'::jsonb, 'Creepy-intimate — dread that builds and stays', '[{"label": "Dread", "value": "High", "level": 3}, {"label": "Gore", "value": "Moderate", "level": 2}, {"label": "Emotion", "value": "Strong", "level": 2}, {"label": "Humor", "value": "Minimal", "level": 1}]'::jsonb, 'Horror fans who rate Hereditary over slashers', 'Solo or with one brave friend, phone away', 'Its fixation themes are deliberately uncomfortable', 'Careful what you wish for, indeed', 'Barker builds the scares out of behavior rather than shadows: the horror is watching a wish rewrite a person. Inde Navarrette gives a physical, unnerving performance the whole film leans on. It is intense company for a night — but the good kind of horror, the kind that follows you to bed.', 'evil-dead-burn', '["Same year, opposite style — pure splatter energy", "For when you''d rather laugh-scream than squirm"]'::jsonb, null, null, 'CineTonight Editorial')
on conflict (id) do update set verdict_headline=excluded.verdict_headline, watch_if=excluded.watch_if, skip_if=excluded.skip_if, chips=excluded.chips, mood=excluded.mood, pace=excluded.pace, intensity=excluded.intensity, attention=excluded.attention, themes=excluded.themes, vibe=excluded.vibe, expect=excluded.expect, best_for_who=excluded.best_for_who, best_for_context=excluded.best_for_context, best_for_caution=excluded.best_for_caution, take_title=excluded.take_title, take_body=excluded.take_body, alt_id=excluded.alt_id, alt_reasons=excluded.alt_reasons, episode_rhythm=excluded.episode_rhythm, hook_expectation=excluded.hook_expectation, editor=excluded.editor, updated_at=now(), reviewed_at=now();

insert into public.movie_intel (id, verdict_headline, watch_if, skip_if, chips, mood, pace, intensity, attention, themes, vibe, expect, best_for_who, best_for_context, best_for_caution, take_title, take_body, alt_id, alt_reasons, episode_rhythm, hook_expectation, editor)
values ('house-of-the-dragon', 'Back to full power — the dance of the dragons finally delivers.', '["You want big-canvas political fantasy with real momentum again", "Dragon spectacle at its television peak", "You dropped it in season 2 and wonder if it recovered — it did"]'::jsonb, '["You need a completed story tonight — the final season is still to come", "Court-politics stretches frustrate you"]'::jsonb, '["Epic TV", "Serialized", "High stakes"]'::jsonb, 'Grand', 'steady', 'high', 'normal', '["Succession", "Civil war", "The cost of power"]'::jsonb, 'Fire-and-blood opera with human stakes', '[{"label": "Spectacle", "value": "Huge", "level": 3}, {"label": "Intrigue", "value": "Dense", "level": 3}, {"label": "Emotion", "value": "Strong", "level": 2}, {"label": "Humor", "value": "Scarce", "level": 1}]'::jsonb, 'Viewers who want Game of Thrones-scale fantasy', 'An evenings-across-two-weeks binge', 'Season 4 concludes the story — expect a wait', 'The correction the show needed', 'Season 3 fixes the complaint that mattered: things happen. The dragon battles are the best the franchise has produced, Emma D''Arcy keeps the civil war human, and the new Hightower commander steals scenes. Pacing still wobbles and some favourites wait their turn, but this is the show at the height of its powers — with one season to go.', null, '[]'::jsonb, 'serialized', 'Give it 2 episodes — season 3 opens strong', 'CineTonight Editorial')
on conflict (id) do update set verdict_headline=excluded.verdict_headline, watch_if=excluded.watch_if, skip_if=excluded.skip_if, chips=excluded.chips, mood=excluded.mood, pace=excluded.pace, intensity=excluded.intensity, attention=excluded.attention, themes=excluded.themes, vibe=excluded.vibe, expect=excluded.expect, best_for_who=excluded.best_for_who, best_for_context=excluded.best_for_context, best_for_caution=excluded.best_for_caution, take_title=excluded.take_title, take_body=excluded.take_body, alt_id=excluded.alt_id, alt_reasons=excluded.alt_reasons, episode_rhythm=excluded.episode_rhythm, hook_expectation=excluded.hook_expectation, editor=excluded.editor, updated_at=now(), reviewed_at=now();

insert into public.movie_intel (id, verdict_headline, watch_if, skip_if, chips, mood, pace, intensity, attention, themes, vibe, expect, best_for_who, best_for_context, best_for_caution, take_title, take_body, alt_id, alt_reasons, episode_rhythm, hook_expectation, editor)
values ('bleach', 'A shonen classic whose highs are enormous — if you ride out the long stretches.', '["You want a big, stylish action anime with an iconic run of arcs", "The Soul Society arc alone justifies the entry price"]'::jsonb, '["Hundreds of episodes with filler between peaks sounds exhausting"]'::jsonb, '["Shonen action", "Long haul", "Casual"]'::jsonb, 'High-energy', 'steady', 'moderate', 'casual', '["Duty", "Friendship", "The afterlife"]'::jsonb, 'Cool-factor first — swords, spirits and swagger', '[{"label": "Action", "value": "High", "level": 3}, {"label": "Humor", "value": "Regular", "level": 2}, {"label": "Emotion", "value": "Moderate", "level": 2}, {"label": "Consistency", "value": "Uneven", "level": 1}]'::jsonb, 'Anime fans starting a classic', 'A long-running comfort binge, arc guide handy', 'Substantial filler sits between the great arcs', 'Start it for Soul Society, stay for the style', 'Bleach earns its classic status in bursts: the Soul Society arc is one of shonen''s best runs, the character design still lands, and the fights carry real weight. Between the peaks, filler drags — keep an arc guide open and skip without guilt. It is the rare long series that gets better the choosier you are.', null, '[]'::jsonb, 'hybrid', 'Give it until the Soul Society arc begins — then it grips', 'CineTonight Editorial')
on conflict (id) do update set verdict_headline=excluded.verdict_headline, watch_if=excluded.watch_if, skip_if=excluded.skip_if, chips=excluded.chips, mood=excluded.mood, pace=excluded.pace, intensity=excluded.intensity, attention=excluded.attention, themes=excluded.themes, vibe=excluded.vibe, expect=excluded.expect, best_for_who=excluded.best_for_who, best_for_context=excluded.best_for_context, best_for_caution=excluded.best_for_caution, take_title=excluded.take_title, take_body=excluded.take_body, alt_id=excluded.alt_id, alt_reasons=excluded.alt_reasons, episode_rhythm=excluded.episode_rhythm, hook_expectation=excluded.hook_expectation, editor=excluded.editor, updated_at=now(), reviewed_at=now();
